<?php
/**
 * Folix Game Theme - Logo Template
 * 
 * @category  Design
 * @package   Folix_GameTheme
 */

/** @var \Magento\Theme\Block\Html\Header\Logo $block */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <?php if ($block->isHomePage()): ?>
        <strong><?= /* @escapeNotVerified */ $storeName ?></strong>
    <?php endif; ?>
    <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
         alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
         <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
         <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />
</a>
